import os
import sys
import subprocess
import time

def main():
    root_dir = os.path.abspath(os.path.dirname(__file__))
    img_path = os.path.join(root_dir, "aetheros.img")
    serial_log = os.path.join(root_dir, "serial.log")
    
    if not os.path.exists(img_path):
        print(f"[ERROR] aetheros.img not found at {img_path}. Build the image first!")
        sys.exit(1)

    # Remove stale serial log
    if os.path.exists(serial_log):
        try:
            os.remove(serial_log)
        except Exception as e:
            print(f"[WARNING] Could not remove old serial.log: {e}")

    qemu_path = "C:/Program Files/qemu/qemu-system-i386.exe"
    if not os.path.exists(qemu_path):
        print(f"[ERROR] QEMU not found at {qemu_path}")
        sys.exit(1)

    print("[AUDIT] Launching QEMU headless boot audit...")
    cmd = [
        qemu_path,
        "-drive", f"file={img_path},format=raw",
        "-display", "none",
        "-serial", f"file:{serial_log}",
        "-d", "int,cpu_reset,guest_errors"
    ]

    # Start QEMU process
    proc = None
    try:
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except Exception as e:
        print(f"[ERROR] Failed to start QEMU: {e}")
        sys.exit(1)

    # Monitor QEMU for 5 seconds
    print("[AUDIT] Running AetherOS for 5 seconds to verify stability...")
    duration = 5.0
    start_time = time.time()
    crashed = False
    
    while time.time() - start_time < duration:
        ret = proc.poll()
        if ret is not None:
            # QEMU exited early! This is usually a crash or a termination
            print(f"[ERROR] QEMU terminated prematurely with exit code {ret}!")
            crashed = True
            break
        time.sleep(0.5)

    if not crashed:
        print("[AUDIT] Terminating QEMU (5-second stability mark reached).")
        proc.terminate()
        try:
            proc.wait(timeout=2)
        except subprocess.TimeoutExpired:
            print("[AUDIT] Force-killing QEMU...")
            proc.kill()
            proc.wait()

    # Get stdout/stderr from QEMU
    stdout, stderr = proc.communicate()
    if stdout:
        print("[QEMU STDOUT]")
        print(stdout.decode(errors='ignore'))
    if stderr:
        print("[QEMU STDERR]")
        print(stderr.decode(errors='ignore'))

    # Inspect serial log
    has_panics = False
    log_content = ""
    if os.path.exists(serial_log):
        try:
            with open(serial_log, "r", encoding="utf-8", errors="ignore") as f:
                log_content = f.read()
            print("\n[AUDIT] --- Serial Log Output ---")
            print(log_content)
            print("[AUDIT] -------------------------\n")
        except Exception as e:
            print(f"[WARNING] Could not read serial log: {e}")
    else:
        print("[WARNING] No serial.log was generated by QEMU.")

    # List of bad strings indicating a crash or panic
    panic_indicators = [
        "panic", "double fault", "triple fault", "general protection fault", 
        "page fault", "exception", "halted", "assertion failed", "crash"
    ]

    for indicator in panic_indicators:
        if indicator in log_content.lower():
            print(f"[CRITICAL ERROR] Panic/Crash indicator '{indicator}' found in serial output!")
            has_panics = True

    if crashed or has_panics:
        print("[AUDIT] RESULT: FAIL - The kernel crashed, panicked, or exited early.")
        sys.exit(1)
    else:
        print("[AUDIT] RESULT: SUCCESS - The kernel booted and ran without any detected panics, crashes, or premature exits.")
        sys.exit(0)

if __name__ == "__main__":
    main()
